# Generated by Django 2.2.19 on 2021-03-15 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendordetail',
            name='testEmailField',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
